name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Run executable
      run: ./build/Release/BuildCICD.exe